;this file for FamiTone2 library generated by text2data tool

bare_metal_soundtrack_music_data:
	.byte 3
	.word @instruments
	.word @samples-3
	.word @song0ch0,@song0ch1,@song0ch2,@song0ch3,@song0ch4,307,256 ; Doom - pmiller
	.word @song1ch0,@song1ch1,@song1ch2,@song1ch3,@song1ch4,307,256 ; Inevitable Doom - celestialghost8
	.word @song2ch0,@song2ch1,@song2ch2,@song2ch3,@song2ch4,307,256 ; Jazz - pmiller

@instruments:
	.byte $30 ;instrument $00
	.word @env1,@env0,@env0
	.byte $00
	.byte $70 ;instrument $01
	.word @env2,@env14,@env0
	.byte $00
	.byte $30 ;instrument $02
	.word @env3,@env0,@env0
	.byte $00
	.byte $30 ;instrument $03
	.word @env4,@env0,@env0
	.byte $00
	.byte $30 ;instrument $04
	.word @env6,@env15,@env0
	.byte $00
	.byte $30 ;instrument $05
	.word @env7,@env0,@env0
	.byte $00
	.byte $30 ;instrument $06
	.word @env5,@env0,@env0
	.byte $00
	.byte $30 ;instrument $07
	.word @env7,@env0,@env0
	.byte $00
	.byte $30 ;instrument $0a
	.word @env13,@env0,@env0
	.byte $00
	.byte $30 ;instrument $0c
	.word @env8,@env0,@env0
	.byte $00
	.byte $30 ;instrument $0d
	.word @env8,@env14,@env0
	.byte $00
	.byte $70 ;instrument $0f
	.word @env1,@env0,@env0
	.byte $00
	.byte $30 ;instrument $11
	.word @env10,@env0,@env0
	.byte $00
	.byte $30 ;instrument $12
	.word @env11,@env16,@env0
	.byte $00
	.byte $70 ;instrument $14
	.word @env9,@env17,@env0
	.byte $00
	.byte $b0 ;instrument $15
	.word @env12,@env0,@env0
	.byte $00
	.byte $30 ;instrument $17
	.word @env8,@env18,@env0
	.byte $00

@samples:
@env0:
	.byte $c0,$00,$00
@env1:
	.byte $c2,$c3,$c5,$c7,$cb,$cd,$cb,$c7,$c5,$c3,$c2,$03,$c2,$00,$09
@env2:
	.byte $c8,$cc,$cd,$02,$cc,$cb,$ca,$c9,$00,$07
@env3:
	.byte $cf,$00,$00
@env4:
	.byte $ce,$cc,$c9,$c0,$00,$03
@env5:
	.byte $cf,$cf,$ce,$cd,$ca,$c6,$c3,$c0,$00,$07
@env6:
	.byte $cf,$cf,$ce,$cd,$ca,$c6,$c0,$00,$06
@env7:
	.byte $ce,$ce,$cd,$ca,$c6,$c0,$00,$05
@env8:
	.byte $c2,$c3,$c5,$c7,$cb,$cd,$00,$05
@env9:
	.byte $cc,$cb,$ca,$c9,$c8,$c7,$c6,$c5,$c4,$c3,$c2,$c1,$c0,$00,$0c
@env10:
	.byte $c3,$00,$00
@env11:
	.byte $c2,$c3,$c4,$c5,$c7,$c3,$0a,$c2,$c3,$03,$c2,$04,$c1,$04,$c0,$00
	.byte $0e
@env12:
	.byte $c9,$00,$00
@env13:
	.byte $c1,$c2,$c3,$c4,$c5,$c7,$c9,$cb,$cc,$cd,$cb,$c7,$c5,$c3,$c2,$03
	.byte $c2,$00,$0d
@env14:
	.byte $b4,$c0,$00,$01
@env15:
	.byte $c1,$c0,$c1,$00,$02
@env16:
	.byte $c0,$c2,$c3,$c5,$c1,$c5,$02,$c6,$03,$c7,$04,$c8,$00,$0b
@env17:
	.byte $c0,$c7,$cc,$c0,$b9,$b4,$c0,$c7,$cc,$c0,$b9,$00,$00
@env18:
	.byte $c0,$bb,$c7,$bb,$00,$00


; Doom - pmiller
@song0ch0:
	.byte $fb,$03
@song0ch0loop:
@ref0:
	.byte $92,$1a,$8d,$1e,$8d,$1e,$8d,$06,$8d,$1e,$9d,$1e,$8d,$06,$8d
@ref1:
	.byte $1e,$9d,$1e,$8d,$06,$8d,$1a,$8d,$1e,$8d,$1e,$8d,$06,$8d
@ref2:
	.byte $1a,$8d,$1e,$8d,$1e,$8d,$06,$8d,$1e,$9d,$1e,$8d,$06,$8d
@ref3:
	.byte $12,$9d,$12,$9d,$12,$8d,$10,$8d,$0c,$9d
	.byte $ff,$0e
	.word @ref2
	.byte $ff,$0e
	.word @ref1
	.byte $ff,$0e
	.word @ref2
	.byte $ff,$0a
	.word @ref3
	.byte $ff,$0e
	.word @ref2
	.byte $ff,$0e
	.word @ref1
	.byte $ff,$0e
	.word @ref2
	.byte $ff,$0a
	.word @ref3
	.byte $ff,$0e
	.word @ref2
	.byte $ff,$0e
	.word @ref1
	.byte $ff,$0e
	.word @ref2
@ref15:
	.byte $12,$8d,$10,$ad,$10,$8d,$0c,$ad
@ref16:
	.byte $a0,$14,$8d,$14,$8d,$14,$8d,$14,$8d,$14,$8d,$14,$8d,$14,$8d,$14
	.byte $8d
@ref17:
	.byte $14,$8d,$14,$8d,$14,$8d,$14,$8d,$14,$8d,$14,$8d,$14,$8d,$92,$14
	.byte $8d
	.byte $fd
	.word @song0ch0loop

; Doom - pmiller
@song0ch1:
@song0ch1loop:
@ref18:
	.byte $92,$28,$8d,$2c,$8d,$2c,$8d,$14,$8d,$2c,$9d,$2c,$8d,$14,$8d
@ref19:
	.byte $2c,$9d,$2c,$8d,$14,$8d,$28,$8d,$2c,$8d,$2c,$8d,$14,$8d
@ref20:
	.byte $28,$8d,$2c,$8d,$2c,$8d,$14,$8d,$2c,$9d,$2c,$8d,$14,$8d
@ref21:
	.byte $20,$9d,$20,$9d,$20,$8d,$1e,$8d,$1a,$9d
	.byte $ff,$0e
	.word @ref20
	.byte $ff,$0e
	.word @ref19
	.byte $ff,$0e
	.word @ref20
	.byte $ff,$0a
	.word @ref21
@ref26:
	.byte $28,$8d,$2c,$8d,$4b,$4e,$99,$44,$bd
	.byte $ff,$0e
	.word @ref19
@ref28:
	.byte $28,$8d,$2c,$8d,$4b,$4e,$99,$54,$9d,$4e,$9d
	.byte $ff,$0a
	.word @ref21
	.byte $ff,$09
	.word @ref26
	.byte $ff,$0e
	.word @ref19
@ref32:
	.byte $28,$8d,$2c,$8d,$4b,$4e,$99,$4b,$4e,$99,$4b,$4e,$99
@ref33:
	.byte $20,$8d,$1e,$ad,$1e,$8d,$1a,$ad
@ref34:
	.byte $0a,$8d,$0a,$8d,$0a,$8d,$0a,$8d,$0a,$8d,$0a,$8d,$0a,$8d,$0a,$8d
@ref35:
	.byte $0a,$8d,$0a,$8d,$0a,$8d,$0a,$8d,$0a,$8d,$0a,$8d,$1e,$8d,$22,$8d
	.byte $fd
	.word @song0ch1loop

; Doom - pmiller
@song0ch2:
@song0ch2loop:
@ref36:
	.byte $94,$32,$8d,$36,$8d,$36,$8d,$1e,$8d,$36,$9d,$36,$8d,$1e,$8d
@ref37:
	.byte $36,$9d,$36,$8d,$1e,$8d,$32,$8d,$36,$8d,$36,$8d,$1e,$8d
@ref38:
	.byte $32,$8d,$36,$8d,$36,$8d,$1e,$8d,$36,$9d,$36,$8d,$1e,$8d
@ref39:
	.byte $2a,$9d,$2a,$9d,$2a,$8d,$28,$8d,$24,$9d
	.byte $ff,$0e
	.word @ref38
	.byte $ff,$0e
	.word @ref37
	.byte $ff,$0e
	.word @ref38
	.byte $ff,$0a
	.word @ref39
@ref44:
	.byte $32,$8d,$36,$8d,$44,$8d,$2c,$8d,$44,$9d,$44,$8d,$2c,$8d
	.byte $ff,$0e
	.word @ref37
	.byte $ff,$0e
	.word @ref44
	.byte $ff,$0a
	.word @ref39
	.byte $ff,$0e
	.word @ref44
	.byte $ff,$0e
	.word @ref37
	.byte $ff,$0e
	.word @ref44
@ref51:
	.byte $2a,$8d,$28,$ad,$28,$8d,$24,$ad
@ref52:
	.byte $14,$8d,$14,$8d,$14,$8d,$14,$8d,$14,$8d,$14,$8d,$14,$8d,$14,$83
	.byte $20,$83,$1e,$81
@ref53:
	.byte $2c,$8d,$2c,$8d,$2c,$8d,$2c,$8d,$2c,$8d,$2c,$8d,$1e,$8d,$3a,$83
	.byte $38,$83,$36,$81
	.byte $fd
	.word @song0ch2loop

; Doom - pmiller
@song0ch3:
@song0ch3loop:
@ref54:
	.byte $88,$02,$8d,$02,$8d,$8a,$0a,$8d,$88,$02,$8d,$02,$9d,$8a,$0a,$8d
	.byte $88,$02,$8d
@ref55:
	.byte $02,$9d,$8a,$0a,$8d,$88,$02,$8d,$02,$8d,$02,$8d,$8a,$0a,$8d,$88
	.byte $02,$8d
@ref56:
	.byte $02,$8d,$02,$8d,$8a,$0a,$8d,$88,$02,$8d,$02,$9d,$8a,$0a,$8d,$88
	.byte $02,$8d
@ref57:
	.byte $02,$9d,$02,$9d,$02,$8d,$02,$8d,$8a,$0a,$8d,$0a,$85,$0a,$85
	.byte $ff,$0e
	.word @ref54
	.byte $ff,$0e
	.word @ref55
	.byte $ff,$0e
	.word @ref56
	.byte $ff,$0e
	.word @ref57
	.byte $ff,$0e
	.word @ref54
	.byte $ff,$0e
	.word @ref55
	.byte $ff,$0e
	.word @ref56
	.byte $ff,$0e
	.word @ref57
	.byte $ff,$0e
	.word @ref54
	.byte $ff,$0e
	.word @ref55
	.byte $ff,$0e
	.word @ref56
@ref69:
	.byte $02,$8d,$02,$8d,$8a,$0a,$9d,$88,$02,$8d,$02,$8d,$8a,$0a,$8d,$0a
	.byte $85,$0a,$85
@ref70:
	.byte $88,$02,$8d,$02,$8d,$02,$8d,$02,$8d,$02,$8d,$02,$8d,$02,$8d,$02
	.byte $87,$8a,$0a,$83
@ref71:
	.byte $88,$02,$8d,$02,$8d,$8a,$0a,$8d,$88,$02,$8d,$02,$8d,$02,$8d,$8a
	.byte $0a,$8d,$0a,$8d
	.byte $fd
	.word @song0ch3loop

; Doom - pmiller
@song0ch4:
@song0ch4loop:
@ref72:
	.byte $f9,$85
@ref73:
	.byte $f9,$85
@ref74:
	.byte $f9,$85
@ref75:
	.byte $f9,$85
@ref76:
	.byte $f9,$85
@ref77:
	.byte $f9,$85
@ref78:
	.byte $f9,$85
@ref79:
	.byte $f9,$85
@ref80:
	.byte $f9,$85
@ref81:
	.byte $f9,$85
@ref82:
	.byte $f9,$85
@ref83:
	.byte $f9,$85
@ref84:
	.byte $f9,$85
@ref85:
	.byte $f9,$85
@ref86:
	.byte $f9,$85
@ref87:
	.byte $f9,$85
@ref88:
	.byte $f9,$85
@ref89:
	.byte $f9,$85
	.byte $fd
	.word @song0ch4loop


; Inevitable Doom - celestialghost8
@song1ch0:
	.byte $fb,$09
@song1ch0loop:
@ref90:
	.byte $96,$02,$00,$02,$00,$83,$02,$00,$02,$00,$8b,$02,$00,$02,$00,$83
	.byte $02,$00,$02,$00,$83,$08,$00,$83,$02,$00,$02,$00,$83,$02,$00,$02
	.byte $00,$8b,$02,$00,$02,$00,$83,$02,$00,$02,$00,$83,$08,$00,$08,$81
@ref91:
	.byte $02,$00,$02,$00,$83,$02,$00,$02,$00,$8b,$02,$00,$02,$00,$83,$02
	.byte $00,$02,$00,$83,$08,$00,$83,$02,$00,$02,$00,$83,$02,$00,$02,$00
	.byte $8b,$02,$00,$02,$00,$83,$02,$00,$02,$00,$83,$08,$00,$08,$81
	.byte $ff,$2f
	.word @ref91
	.byte $ff,$2f
	.word @ref91
	.byte $ff,$2f
	.word @ref91
	.byte $ff,$2f
	.word @ref91
	.byte $ff,$2f
	.word @ref91
	.byte $ff,$2f
	.word @ref91
	.byte $fd
	.word @song1ch0loop

; Inevitable Doom - celestialghost8
@song1ch1:
@song1ch1loop:
@ref98:
	.byte $96,$1a,$00,$1a,$00,$83,$1a,$00,$1a,$00,$8b,$1a,$00,$1a,$00,$83
	.byte $1a,$00,$1a,$00,$83,$20,$00,$83,$1a,$00,$1a,$00,$83,$1a,$00,$1a
	.byte $00,$8b,$1a,$00,$1a,$00,$83,$1a,$00,$1a,$00,$83,$20,$00,$20,$81
@ref99:
	.byte $1a,$00,$1a,$00,$83,$1a,$00,$1a,$00,$8b,$1a,$00,$1a,$00,$83,$1a
	.byte $00,$1a,$00,$83,$20,$00,$83,$1a,$00,$1a,$00,$83,$1a,$00,$1a,$00
	.byte $8b,$1a,$00,$1a,$00,$83,$1a,$00,$1a,$00,$83,$20,$00,$20,$81
@ref100:
	.byte $20,$95,$1e,$85,$1a,$9b,$00,$1b,$1f,$20,$85,$1e,$85,$21,$1f,$1a
	.byte $9d
@ref101:
	.byte $28,$95,$24,$85,$20,$95,$1b,$1f,$20,$8d,$1e,$87,$00,$1e,$20,$1a
	.byte $9d
	.byte $ff,$2f
	.word @ref99
@ref103:
	.byte $20,$1e,$20,$85,$1e,$20,$1e,$8d,$1a,$16,$1a,$99,$1a,$1e,$20,$24
	.byte $21,$1e,$20,$24,$20,$25,$20,$24,$28,$2a,$28,$26,$28,$99
@ref104:
	.byte $32,$2e,$32,$85,$28,$2a,$28,$8d,$24,$20,$28,$99,$24,$20,$24,$85
	.byte $20,$85,$1f,$20,$1e,$1b,$17,$1a,$99
@ref105:
	.byte $32,$00,$32,$85,$32,$00,$32,$8d,$32,$00,$32,$85,$32,$00,$32,$85
	.byte $2e,$00,$2e,$2e,$32,$00,$32,$85,$32,$00,$32,$8d,$32,$00,$32,$85
	.byte $32,$00,$32,$85,$28,$2a,$1e,$20
	.byte $fd
	.word @song1ch1loop

; Inevitable Doom - celestialghost8
@song1ch2:
@song1ch2loop:
@ref106:
	.byte $98,$6a,$00,$6a,$00,$83,$6a,$00,$6a,$00,$8b,$6a,$00,$6a,$00,$83
	.byte $6a,$00,$6a,$00,$8b,$6a,$00,$6a,$00,$83,$6a,$00,$6a,$00,$8b,$6a
	.byte $00,$6a,$00,$83,$6a,$00,$6a,$00,$8b
@ref107:
	.byte $6a,$00,$6a,$00,$83,$6a,$00,$6a,$00,$8b,$6a,$00,$6a,$00,$83,$6a
	.byte $00,$6a,$00,$8b,$6a,$00,$6a,$00,$83,$6a,$00,$6a,$00,$8b,$6a,$00
	.byte $6a,$00,$83,$6a,$00,$6a,$00,$8b
	.byte $ff,$28
	.word @ref107
	.byte $ff,$28
	.word @ref107
	.byte $ff,$28
	.word @ref107
	.byte $ff,$28
	.word @ref107
	.byte $ff,$28
	.word @ref107
	.byte $ff,$28
	.word @ref107
	.byte $fd
	.word @song1ch2loop

; Inevitable Doom - celestialghost8
@song1ch3:
@song1ch3loop:
@ref114:
	.byte $97,$9a,$06,$85,$00,$95,$07,$07,$00,$95,$06,$85,$00,$95,$07,$06
	.byte $81
@ref115:
	.byte $97,$06,$85,$00,$95,$07,$07,$00,$95,$06,$85,$00,$95,$07,$06,$81
	.byte $ff,$10
	.word @ref115
	.byte $ff,$10
	.word @ref115
	.byte $ff,$10
	.word @ref115
	.byte $ff,$10
	.word @ref115
	.byte $ff,$10
	.word @ref115
	.byte $ff,$10
	.word @ref115
	.byte $fd
	.word @song1ch3loop

; Inevitable Doom - celestialghost8
@song1ch4:
@song1ch4loop:
@ref122:
	.byte $f9,$85
@ref123:
	.byte $f9,$85
@ref124:
	.byte $f9,$85
@ref125:
	.byte $f9,$85
@ref126:
	.byte $f9,$85
@ref127:
	.byte $f9,$85
@ref128:
	.byte $f9,$85
@ref129:
	.byte $f9,$85
	.byte $fd
	.word @song1ch4loop


; Jazz - pmiller
@song2ch0:
	.byte $fb,$02
@song2ch0loop:
@ref130:
	.byte $80,$3c,$89,$00,$89,$3c,$89,$00,$89,$4a,$a1
@ref131:
	.byte $3c,$89,$00,$89,$3c,$89,$00,$89,$4a,$a1
	.byte $ff,$0a
	.word @ref131
@ref133:
	.byte $3c,$89,$00,$89,$3c,$89,$00,$89,$82,$44,$89,$4a,$89,$4e,$89
@ref134:
	.byte $54,$89,$4e,$c5
@ref135:
	.byte $c3,$58,$85,$54,$85
@ref136:
	.byte $4e,$85,$54,$85,$4e,$85,$44,$b9
@ref137:
	.byte $af,$44,$89,$4a,$89,$4e,$89
@ref138:
	.byte $54,$89,$58,$89,$54,$89,$58,$95,$54,$95
@ref139:
	.byte $58,$ad,$54,$89,$4e,$89,$40,$89
@ref140:
	.byte $44,$d1
@ref141:
	.byte $d3
@ref142:
	.byte $62,$8d,$58,$8d,$9e,$58,$8d,$82,$58,$a1
@ref143:
	.byte $c7,$58,$89
@ref144:
	.byte $52,$a1,$44,$ad
@ref145:
	.byte $c7,$58,$89
@ref146:
	.byte $62,$8d,$62,$8d,$62,$8d,$62,$a1
@ref147:
	.byte $af,$58,$a1
@ref148:
	.byte $44,$d1
	.byte $ff,$07
	.word @ref137
@ref150:
	.byte $54,$a1,$4e,$ad
@ref151:
	.byte $c7,$58,$89
@ref152:
	.byte $54,$a1,$44,$ad
	.byte $ff,$07
	.word @ref137
@ref154:
	.byte $54,$8d,$58,$8d,$54,$8d,$58,$8d,$54,$8d,$58,$81
@ref155:
	.byte $a9,$44,$4a,$4e,$54,$a1
@ref156:
	.byte $8f,$9e,$4e,$c1
@ref157:
	.byte $d3
	.byte $ff,$0a
	.word @ref130
	.byte $ff,$0a
	.word @ref131
	.byte $ff,$0a
	.word @ref131
@ref161:
	.byte $3c,$89,$00,$89,$3c,$89,$00,$89,$44,$a1
@ref162:
	.byte $3c,$89,$9c,$5c,$89,$80,$3c,$89,$00,$89,$4a,$a1
	.byte $ff,$0a
	.word @ref162
	.byte $ff,$0a
	.word @ref162
	.byte $ff,$0a
	.word @ref162
	.byte $ff,$0a
	.word @ref162
	.byte $ff,$0a
	.word @ref162
	.byte $ff,$0a
	.word @ref162
@ref169:
	.byte $3c,$89,$9c,$5c,$89,$80,$3c,$89,$9c,$52,$89,$80,$4a,$a1
@ref170:
	.byte $42,$89,$9c,$62,$89,$80,$42,$89,$9c,$5a,$89,$90,$4a,$a1
@ref171:
	.byte $80,$42,$89,$9c,$62,$89,$80,$42,$89,$9c,$5a,$89,$90,$4a,$a1
@ref172:
	.byte $80,$3c,$89,$9c,$5c,$89,$80,$3c,$89,$9c,$52,$89,$90,$4a,$a1
	.byte $ff,$0a
	.word @ref172
	.byte $ff,$0a
	.word @ref171
	.byte $ff,$0a
	.word @ref171
	.byte $ff,$0a
	.word @ref172
@ref177:
	.byte $80,$3c,$89,$9c,$52,$89,$80,$3c,$89,$9c,$54,$89,$90,$4c,$a1
@ref178:
	.byte $80,$3c,$89,$9c,$5c,$89,$80,$3c,$89,$00,$89,$4a,$a1
@ref179:
	.byte $3c,$89,$00,$89,$3c,$89,$9c,$5c,$89,$80,$4a,$a1
	.byte $ff,$0a
	.word @ref162
	.byte $ff,$0a
	.word @ref179
	.byte $ff,$0a
	.word @ref162
	.byte $ff,$0a
	.word @ref179
	.byte $ff,$0a
	.word @ref162
@ref185:
	.byte $3c,$89,$00,$89,$3c,$89,$9c,$5c,$89,$80,$4a,$89,$00,$95
@ref186:
	.byte $00,$89,$9c,$62,$95,$5a,$ad
@ref187:
	.byte $8b,$62,$95,$5a,$ad
@ref188:
	.byte $8b,$5c,$95,$52,$ad
	.byte $ff,$05
	.word @ref188
	.byte $ff,$05
	.word @ref187
	.byte $ff,$05
	.word @ref187
	.byte $ff,$05
	.word @ref188
@ref193:
	.byte $8b,$52,$95,$54,$89,$80,$44,$89,$4a,$89,$4e,$89
	.byte $ff,$0a
	.word @ref162
	.byte $ff,$0a
	.word @ref179
	.byte $ff,$0a
	.word @ref162
	.byte $ff,$0a
	.word @ref179
	.byte $ff,$0a
	.word @ref162
	.byte $ff,$0a
	.word @ref179
	.byte $ff,$0a
	.word @ref162
	.byte $ff,$0e
	.word @ref133
@ref202:
	.byte $54,$89,$4e,$c5
	.byte $ff,$05
	.word @ref135
	.byte $ff,$08
	.word @ref136
	.byte $ff,$07
	.word @ref137
	.byte $ff,$0a
	.word @ref138
	.byte $ff,$08
	.word @ref139
@ref208:
	.byte $44,$d1
@ref209:
	.byte $d3
	.byte $ff,$08
	.word @ref142
@ref211:
	.byte $c7,$58,$89
@ref212:
	.byte $52,$a1,$44,$ad
@ref213:
	.byte $c7,$58,$89
	.byte $ff,$08
	.word @ref146
@ref215:
	.byte $af,$58,$a1
@ref216:
	.byte $44,$d1
	.byte $ff,$07
	.word @ref137
@ref218:
	.byte $54,$a1,$4e,$ad
@ref219:
	.byte $c7,$58,$89
@ref220:
	.byte $54,$a1,$44,$ad
	.byte $ff,$07
	.word @ref137
	.byte $ff,$0c
	.word @ref154
	.byte $ff,$06
	.word @ref155
@ref224:
	.byte $8f,$9e,$4e,$c1
@ref225:
	.byte $af,$82,$54,$a1
@ref226:
	.byte $8f,$9e,$4e,$c1
@ref227:
	.byte $af,$82,$54,$a1
@ref228:
	.byte $8f,$9e,$4e,$c1
@ref229:
	.byte $a9,$00,$a7
	.byte $fd
	.word @song2ch0loop

; Jazz - pmiller
@song2ch1:
@song2ch1loop:
@ref230:
	.byte $80,$44,$89,$00,$89,$44,$89,$00,$89,$52,$a1
@ref231:
	.byte $44,$89,$00,$89,$44,$89,$00,$89,$52,$a1
	.byte $ff,$0a
	.word @ref231
	.byte $ff,$0a
	.word @ref231
	.byte $ff,$0a
	.word @ref231
	.byte $ff,$0a
	.word @ref231
	.byte $ff,$0a
	.word @ref231
	.byte $ff,$0a
	.word @ref231
	.byte $ff,$0a
	.word @ref231
	.byte $ff,$0a
	.word @ref231
	.byte $ff,$0a
	.word @ref231
@ref241:
	.byte $44,$89,$00,$89,$44,$89,$00,$89,$46,$a1
@ref242:
	.byte $50,$89,$00,$89,$50,$89,$00,$89,$58,$a1
	.byte $ff,$0a
	.word @ref242
@ref244:
	.byte $4a,$89,$00,$89,$4a,$89,$00,$89,$52,$a1
	.byte $ff,$0a
	.word @ref244
	.byte $ff,$0a
	.word @ref242
	.byte $ff,$0a
	.word @ref242
	.byte $ff,$0a
	.word @ref244
@ref249:
	.byte $4a,$89,$00,$89,$4a,$89,$00,$89,$54,$a1
	.byte $ff,$0a
	.word @ref231
	.byte $ff,$0a
	.word @ref231
	.byte $ff,$0a
	.word @ref231
	.byte $ff,$0a
	.word @ref231
	.byte $ff,$0a
	.word @ref231
	.byte $ff,$0a
	.word @ref231
	.byte $ff,$0a
	.word @ref231
	.byte $ff,$0a
	.word @ref231
	.byte $ff,$0a
	.word @ref231
	.byte $ff,$0a
	.word @ref231
	.byte $ff,$0a
	.word @ref231
	.byte $ff,$0a
	.word @ref231
@ref262:
	.byte $44,$89,$9c,$6a,$89,$80,$44,$89,$00,$89,$52,$a1
	.byte $ff,$0a
	.word @ref262
	.byte $ff,$0a
	.word @ref262
	.byte $ff,$0a
	.word @ref262
	.byte $ff,$0a
	.word @ref262
	.byte $ff,$0a
	.word @ref262
	.byte $ff,$0a
	.word @ref262
@ref269:
	.byte $44,$89,$9c,$6a,$89,$80,$44,$89,$9c,$5c,$89,$80,$46,$a1
@ref270:
	.byte $50,$89,$9c,$70,$89,$80,$50,$89,$9c,$68,$89,$90,$58,$a1
@ref271:
	.byte $80,$50,$89,$9c,$70,$89,$80,$50,$89,$9c,$68,$89,$90,$58,$a1
@ref272:
	.byte $80,$4a,$89,$9c,$6a,$89,$80,$4a,$89,$9c,$5c,$89,$90,$52,$a1
	.byte $ff,$0a
	.word @ref272
	.byte $ff,$0a
	.word @ref271
	.byte $ff,$0a
	.word @ref271
	.byte $ff,$0a
	.word @ref272
@ref277:
	.byte $80,$4a,$89,$9c,$5c,$89,$80,$4a,$89,$9c,$5c,$89,$90,$54,$a1
@ref278:
	.byte $80,$44,$89,$9c,$6a,$89,$80,$44,$89,$00,$89,$52,$a1
@ref279:
	.byte $44,$89,$00,$89,$44,$89,$9c,$6a,$89,$80,$52,$a1
	.byte $ff,$0a
	.word @ref262
	.byte $ff,$0a
	.word @ref279
	.byte $ff,$0a
	.word @ref262
	.byte $ff,$0a
	.word @ref279
	.byte $ff,$0a
	.word @ref262
@ref285:
	.byte $44,$89,$00,$89,$44,$89,$9c,$6a,$89,$80,$52,$89,$00,$95
@ref286:
	.byte $00,$89,$9c,$70,$95,$68,$ad
@ref287:
	.byte $8b,$70,$95,$68,$ad
@ref288:
	.byte $8b,$6a,$95,$5c,$ad
	.byte $ff,$05
	.word @ref288
	.byte $ff,$05
	.word @ref287
	.byte $ff,$05
	.word @ref287
	.byte $ff,$05
	.word @ref288
@ref293:
	.byte $8b,$5c,$95,$5c,$89,$80,$2c,$89,$32,$89,$36,$89
	.byte $ff,$0a
	.word @ref262
	.byte $ff,$0a
	.word @ref279
	.byte $ff,$0a
	.word @ref262
	.byte $ff,$0a
	.word @ref279
	.byte $ff,$0a
	.word @ref262
	.byte $ff,$0a
	.word @ref279
	.byte $ff,$0a
	.word @ref262
	.byte $ff,$0a
	.word @ref231
	.byte $ff,$0a
	.word @ref231
	.byte $ff,$0a
	.word @ref231
	.byte $ff,$0a
	.word @ref231
	.byte $ff,$0a
	.word @ref231
	.byte $ff,$0a
	.word @ref231
	.byte $ff,$0a
	.word @ref231
	.byte $ff,$0a
	.word @ref231
	.byte $ff,$0a
	.word @ref241
	.byte $ff,$0a
	.word @ref242
	.byte $ff,$0a
	.word @ref242
	.byte $ff,$0a
	.word @ref244
	.byte $ff,$0a
	.word @ref244
	.byte $ff,$0a
	.word @ref242
	.byte $ff,$0a
	.word @ref242
	.byte $ff,$0a
	.word @ref244
	.byte $ff,$0a
	.word @ref249
	.byte $ff,$0a
	.word @ref231
	.byte $ff,$0a
	.word @ref231
	.byte $ff,$0a
	.word @ref231
	.byte $ff,$0a
	.word @ref231
	.byte $ff,$0a
	.word @ref231
	.byte $ff,$0a
	.word @ref231
	.byte $ff,$0a
	.word @ref231
	.byte $ff,$0a
	.word @ref231
	.byte $ff,$0a
	.word @ref231
	.byte $ff,$0a
	.word @ref231
@ref328:
	.byte $44,$d1
@ref329:
	.byte $00,$d1
	.byte $fd
	.word @song2ch1loop

; Jazz - pmiller
@song2ch2:
@song2ch2loop:
@ref330:
	.byte $84,$36,$89,$00,$89,$36,$89,$00,$89,$44,$a1
@ref331:
	.byte $36,$89,$00,$89,$36,$89,$00,$89,$44,$a1
	.byte $ff,$0a
	.word @ref331
	.byte $ff,$0a
	.word @ref331
	.byte $ff,$0a
	.word @ref331
	.byte $ff,$0a
	.word @ref331
	.byte $ff,$0a
	.word @ref331
	.byte $ff,$0a
	.word @ref331
	.byte $ff,$0a
	.word @ref331
	.byte $ff,$0a
	.word @ref331
	.byte $ff,$0a
	.word @ref331
@ref341:
	.byte $36,$89,$00,$89,$36,$89,$00,$89,$38,$a1
@ref342:
	.byte $42,$89,$00,$89,$42,$89,$00,$89,$4a,$a1
	.byte $ff,$0a
	.word @ref342
	.byte $ff,$0a
	.word @ref161
	.byte $ff,$0a
	.word @ref161
	.byte $ff,$0a
	.word @ref342
	.byte $ff,$0a
	.word @ref342
	.byte $ff,$0a
	.word @ref161
	.byte $ff,$0a
	.word @ref161
	.byte $ff,$0a
	.word @ref331
	.byte $ff,$0a
	.word @ref331
	.byte $ff,$0a
	.word @ref331
	.byte $ff,$0a
	.word @ref331
	.byte $ff,$0a
	.word @ref331
	.byte $ff,$0a
	.word @ref331
	.byte $ff,$0a
	.word @ref331
	.byte $ff,$0a
	.word @ref331
	.byte $ff,$0a
	.word @ref331
	.byte $ff,$0a
	.word @ref331
	.byte $ff,$0a
	.word @ref331
@ref361:
	.byte $36,$89,$00,$89,$36,$89,$00,$89,$2c,$89,$32,$89,$36,$89
@ref362:
	.byte $3c,$89,$36,$a1,$44,$a1
@ref363:
	.byte $36,$89,$00,$89,$36,$89,$00,$89,$44,$91,$40,$85,$3c,$85
@ref364:
	.byte $36,$85,$3c,$85,$36,$85,$2c,$95,$44,$a1
	.byte $ff,$0e
	.word @ref361
@ref366:
	.byte $3c,$89,$40,$89,$3c,$89,$40,$95,$3c,$95
@ref367:
	.byte $36,$89,$00,$89,$36,$89,$00,$89,$3c,$89,$36,$89,$28,$89
@ref368:
	.byte $2c,$95,$36,$89,$00,$89,$44,$a1
	.byte $ff,$0a
	.word @ref341
@ref370:
	.byte $4a,$8d,$40,$85,$42,$85,$40,$87,$00,$83,$40,$a1
@ref371:
	.byte $42,$89,$00,$89,$42,$89,$00,$89,$4a,$99,$40,$85
@ref372:
	.byte $3a,$95,$3c,$89,$32,$ad
@ref373:
	.byte $3c,$89,$00,$89,$3c,$89,$00,$89,$44,$95,$40,$89
@ref374:
	.byte $4a,$89,$01,$4a,$85,$42,$85,$4a,$87,$00,$83,$4a,$a1
@ref375:
	.byte $42,$89,$00,$89,$42,$89,$00,$89,$4a,$95,$40,$89
@ref376:
	.byte $3a,$89,$00,$89,$3c,$89,$32,$ad
@ref377:
	.byte $3c,$89,$00,$89,$3c,$89,$00,$89,$44,$89,$32,$89,$36,$89
@ref378:
	.byte $3c,$89,$00,$89,$3c,$89,$36,$89,$44,$a1
@ref379:
	.byte $36,$89,$00,$89,$36,$89,$00,$89,$44,$95,$40,$89
@ref380:
	.byte $3c,$89,$00,$89,$3c,$89,$2c,$89,$44,$a1
	.byte $ff,$0e
	.word @ref361
@ref382:
	.byte $3c,$8d,$40,$8d,$3c,$8d,$40,$8d,$3c,$91
@ref383:
	.byte $36,$89,$00,$89,$36,$89,$00,$89,$3c,$95,$32,$89
	.byte $ff,$0a
	.word @ref331
	.byte $ff,$0a
	.word @ref331
@ref386:
	.byte $4a,$89,$a0,$41,$84,$40,$85,$42,$85,$41,$a0,$38,$87,$00,$84,$40
	.byte $a1
@ref387:
	.byte $42,$89,$a0,$40,$89,$84,$42,$89,$a0,$38,$89,$84,$4a,$99,$40,$85
@ref388:
	.byte $3a,$89,$a0,$3a,$89,$84,$3c,$89,$32,$89,$3a,$a1
@ref389:
	.byte $3c,$89,$a0,$3a,$89,$84,$3c,$89,$a0,$30,$89,$84,$44,$95,$40,$89
@ref390:
	.byte $4a,$89,$a0,$41,$84,$4a,$85,$42,$85,$4b,$a0,$38,$89,$84,$4a,$a1
@ref391:
	.byte $42,$89,$a0,$40,$89,$84,$42,$89,$a0,$38,$89,$84,$4a,$95,$40,$89
@ref392:
	.byte $3a,$89,$a0,$3a,$89,$84,$3c,$89,$32,$89,$2c,$a1
@ref393:
	.byte $3c,$89,$a0,$30,$89,$84,$3c,$89,$a0,$34,$89,$84,$2c,$89,$32,$89
	.byte $36,$89
@ref394:
	.byte $3c,$89,$a0,$3a,$89,$84,$3c,$89,$36,$89,$44,$a1
@ref395:
	.byte $36,$89,$00,$89,$36,$89,$a0,$3a,$89,$84,$44,$95,$40,$89
@ref396:
	.byte $3c,$89,$a0,$3a,$89,$84,$3c,$89,$2c,$89,$44,$a1
@ref397:
	.byte $36,$89,$00,$89,$36,$89,$a0,$3a,$89,$84,$2c,$89,$32,$89,$36,$89
@ref398:
	.byte $3c,$89,$a0,$3b,$84,$40,$8d,$3c,$8d,$40,$8d,$3c,$91
@ref399:
	.byte $36,$89,$00,$89,$36,$89,$a0,$3a,$89,$84,$3c,$95,$32,$89
@ref400:
	.byte $36,$89,$a0,$3a,$89,$84,$36,$89,$00,$89,$44,$a1
	.byte $ff,$0a
	.word @ref331
	.byte $ff,$0a
	.word @ref331
	.byte $ff,$0a
	.word @ref331
	.byte $ff,$0a
	.word @ref331
	.byte $ff,$0a
	.word @ref331
	.byte $ff,$0a
	.word @ref331
	.byte $ff,$0a
	.word @ref331
	.byte $ff,$0a
	.word @ref331
	.byte $ff,$0a
	.word @ref341
	.byte $ff,$0a
	.word @ref342
	.byte $ff,$0a
	.word @ref342
	.byte $ff,$0a
	.word @ref161
	.byte $ff,$0a
	.word @ref161
	.byte $ff,$0a
	.word @ref342
	.byte $ff,$0a
	.word @ref342
	.byte $ff,$0a
	.word @ref161
	.byte $ff,$0a
	.word @ref161
	.byte $ff,$0a
	.word @ref331
	.byte $ff,$0a
	.word @ref331
	.byte $ff,$0a
	.word @ref331
	.byte $ff,$0a
	.word @ref331
	.byte $ff,$0a
	.word @ref331
	.byte $ff,$0a
	.word @ref331
	.byte $ff,$0a
	.word @ref331
	.byte $ff,$0a
	.word @ref331
	.byte $ff,$0a
	.word @ref331
	.byte $ff,$0a
	.word @ref331
@ref428:
	.byte $36,$d1
@ref429:
	.byte $00,$d1
	.byte $fd
	.word @song2ch2loop

; Jazz - pmiller
@song2ch3:
@song2ch3loop:
@ref430:
	.byte $8c,$02,$89,$86,$12,$89,$8c,$02,$89,$86,$12,$89,$8e,$0a,$89,$86
	.byte $12,$89,$8e,$0a,$89
@ref431:
	.byte $8c,$02,$89,$86,$12,$89,$8c,$02,$89,$86,$12,$89,$8c,$02,$89,$86
	.byte $12,$89,$8e,$0a,$89
	.byte $ff,$0e
	.word @ref430
@ref433:
	.byte $8c,$02,$89,$86,$12,$89,$8c,$02,$89,$86,$12,$89,$8c,$02,$89,$86
	.byte $12,$89,$8e,$0a,$83,$0a,$83
	.byte $ff,$0e
	.word @ref430
	.byte $ff,$0e
	.word @ref431
	.byte $ff,$0e
	.word @ref430
	.byte $ff,$10
	.word @ref433
	.byte $ff,$0e
	.word @ref430
@ref439:
	.byte $8c,$02,$89,$86,$12,$89,$8c,$02,$89,$86,$12,$89,$8c,$02,$89,$86
	.byte $12,$89,$8c,$20,$89
@ref440:
	.byte $02,$89,$86,$12,$89,$8c,$02,$89,$86,$12,$89,$8e,$0a,$89,$86,$12
	.byte $89,$8e,$0a,$89
@ref441:
	.byte $8c,$02,$89,$86,$12,$89,$8c,$02,$83,$8e,$0a,$83,$86,$12,$89,$8c
	.byte $02,$89,$86,$12,$89,$8e,$0a,$83,$0a,$83
	.byte $ff,$0e
	.word @ref430
	.byte $ff,$0e
	.word @ref431
	.byte $ff,$0e
	.word @ref430
	.byte $ff,$10
	.word @ref433
	.byte $ff,$0e
	.word @ref430
	.byte $ff,$0e
	.word @ref431
	.byte $ff,$0e
	.word @ref430
@ref449:
	.byte $8c,$02,$89,$86,$12,$89,$8e,$0a,$89,$86,$12,$89,$8e,$0a,$89,$8c
	.byte $02,$83,$04,$89,$8e,$0a,$83
@ref450:
	.byte $8c,$02,$89,$86,$12,$83,$12,$83,$8c,$02,$89,$86,$12,$89,$8e,$0a
	.byte $89,$86,$12,$89,$8e,$0a,$89
@ref451:
	.byte $8c,$02,$89,$86,$12,$89,$8c,$02,$89,$86,$12,$89,$8c,$02,$83,$8e
	.byte $0a,$83,$86,$12,$89,$8e,$0a,$89
	.byte $ff,$0e
	.word @ref430
	.byte $ff,$10
	.word @ref433
	.byte $ff,$0e
	.word @ref430
	.byte $ff,$0e
	.word @ref431
	.byte $ff,$0e
	.word @ref430
	.byte $ff,$10
	.word @ref433
@ref458:
	.byte $8c,$02,$89,$86,$12,$89,$8c,$02,$89,$86,$12,$89,$8e,$0a,$89,$86
	.byte $12,$89,$8c,$04,$89
@ref459:
	.byte $02,$89,$86,$12,$89,$8c,$02,$89,$86,$12,$89,$8c,$02,$89,$86,$12
	.byte $89,$8e,$0a,$89
	.byte $ff,$0e
	.word @ref458
@ref461:
	.byte $02,$89,$86,$12,$89,$8c,$02,$89,$86,$12,$89,$8c,$02,$89,$86,$12
	.byte $89,$8e,$0a,$83,$0a,$83
	.byte $ff,$0e
	.word @ref458
	.byte $ff,$0e
	.word @ref459
	.byte $ff,$0e
	.word @ref458
	.byte $ff,$10
	.word @ref461
	.byte $ff,$0e
	.word @ref458
	.byte $ff,$0e
	.word @ref459
	.byte $ff,$0e
	.word @ref458
	.byte $ff,$10
	.word @ref461
	.byte $ff,$0e
	.word @ref458
	.byte $ff,$0e
	.word @ref459
	.byte $ff,$0e
	.word @ref458
	.byte $ff,$10
	.word @ref461
	.byte $ff,$0e
	.word @ref458
	.byte $ff,$0e
	.word @ref459
	.byte $ff,$0e
	.word @ref458
	.byte $ff,$10
	.word @ref461
	.byte $ff,$0e
	.word @ref458
	.byte $ff,$0e
	.word @ref459
	.byte $ff,$0e
	.word @ref458
	.byte $ff,$10
	.word @ref461
	.byte $ff,$0e
	.word @ref458
	.byte $ff,$0e
	.word @ref459
	.byte $ff,$0e
	.word @ref458
	.byte $ff,$10
	.word @ref461
	.byte $ff,$0e
	.word @ref439
@ref487:
	.byte $02,$89,$86,$12,$89,$8c,$02,$89,$86,$12,$89,$8c,$02,$89,$86,$12
	.byte $89,$8c,$20,$89
	.byte $ff,$0e
	.word @ref487
@ref489:
	.byte $02,$89,$86,$12,$89,$8c,$02,$89,$86,$12,$89,$8c,$02,$89,$86,$12
	.byte $89,$8c,$02,$83,$20,$83
	.byte $ff,$0e
	.word @ref487
	.byte $ff,$0e
	.word @ref487
	.byte $ff,$0e
	.word @ref487
@ref493:
	.byte $02,$89,$86,$12,$89,$8e,$0a,$89,$84,$0e,$0c,$0a,$08,$06,$04,$8c
	.byte $02,$83,$04,$83,$02,$83,$8e,$0a,$83,$08,$83,$06,$83
	.byte $ff,$10
	.word @ref450
@ref495:
	.byte $8c,$02,$89,$86,$12,$89,$8c,$02,$89,$86,$12,$83,$12,$83,$8c,$02
	.byte $83,$8e,$0a,$83,$86,$12,$89,$8e,$0a,$89
	.byte $ff,$10
	.word @ref450
@ref497:
	.byte $8c,$02,$89,$86,$12,$89,$8c,$02,$89,$86,$12,$83,$12,$83,$8c,$02
	.byte $89,$86,$12,$89,$8e,$0a,$83,$0a,$83
	.byte $ff,$10
	.word @ref450
	.byte $ff,$12
	.word @ref495
	.byte $ff,$10
	.word @ref450
	.byte $ff,$12
	.word @ref497
	.byte $ff,$0e
	.word @ref430
	.byte $ff,$0e
	.word @ref431
	.byte $ff,$0e
	.word @ref430
	.byte $ff,$10
	.word @ref433
	.byte $ff,$10
	.word @ref450
	.byte $ff,$10
	.word @ref451
	.byte $ff,$0e
	.word @ref430
	.byte $ff,$10
	.word @ref433
	.byte $ff,$0e
	.word @ref430
	.byte $ff,$0e
	.word @ref431
	.byte $ff,$0e
	.word @ref430
	.byte $ff,$10
	.word @ref433
	.byte $ff,$0e
	.word @ref430
	.byte $ff,$0e
	.word @ref431
	.byte $ff,$0e
	.word @ref430
	.byte $ff,$10
	.word @ref433
	.byte $ff,$10
	.word @ref450
	.byte $ff,$10
	.word @ref451
	.byte $ff,$0e
	.word @ref430
	.byte $ff,$10
	.word @ref433
	.byte $ff,$10
	.word @ref450
	.byte $ff,$10
	.word @ref451
	.byte $ff,$0e
	.word @ref430
	.byte $ff,$10
	.word @ref433
	.byte $ff,$0e
	.word @ref430
	.byte $ff,$0e
	.word @ref430
@ref528:
	.byte $84,$12,$10,$0e,$0c,$0a,$08,$06,$04,$02,$20,$bf
@ref529:
	.byte $00,$d1
	.byte $fd
	.word @song2ch3loop

; Jazz - pmiller
@song2ch4:
@song2ch4loop:
@ref530:
	.byte $d3
@ref531:
	.byte $d3
@ref532:
	.byte $d3
@ref533:
	.byte $d3
@ref534:
	.byte $d3
@ref535:
	.byte $d3
@ref536:
	.byte $d3
@ref537:
	.byte $d3
@ref538:
	.byte $d3
@ref539:
	.byte $d3
@ref540:
	.byte $d3
@ref541:
	.byte $d3
@ref542:
	.byte $d3
@ref543:
	.byte $d3
@ref544:
	.byte $d3
@ref545:
	.byte $d3
@ref546:
	.byte $d3
@ref547:
	.byte $d3
@ref548:
	.byte $d3
@ref549:
	.byte $d3
@ref550:
	.byte $d3
@ref551:
	.byte $d3
@ref552:
	.byte $d3
@ref553:
	.byte $d3
@ref554:
	.byte $d3
@ref555:
	.byte $d3
@ref556:
	.byte $d3
@ref557:
	.byte $d3
@ref558:
	.byte $d3
@ref559:
	.byte $d3
@ref560:
	.byte $d3
@ref561:
	.byte $d3
@ref562:
	.byte $d3
@ref563:
	.byte $d3
@ref564:
	.byte $d3
@ref565:
	.byte $d3
@ref566:
	.byte $d3
@ref567:
	.byte $d3
@ref568:
	.byte $d3
@ref569:
	.byte $d3
@ref570:
	.byte $d3
@ref571:
	.byte $d3
@ref572:
	.byte $d3
@ref573:
	.byte $d3
@ref574:
	.byte $d3
@ref575:
	.byte $d3
@ref576:
	.byte $d3
@ref577:
	.byte $d3
@ref578:
	.byte $d3
@ref579:
	.byte $d3
@ref580:
	.byte $d3
@ref581:
	.byte $d3
@ref582:
	.byte $d3
@ref583:
	.byte $d3
@ref584:
	.byte $d3
@ref585:
	.byte $d3
@ref586:
	.byte $d3
@ref587:
	.byte $d3
@ref588:
	.byte $d3
@ref589:
	.byte $d3
@ref590:
	.byte $d3
@ref591:
	.byte $d3
@ref592:
	.byte $d3
@ref593:
	.byte $d3
@ref594:
	.byte $d3
@ref595:
	.byte $d3
@ref596:
	.byte $d3
@ref597:
	.byte $d3
@ref598:
	.byte $d3
@ref599:
	.byte $d3
@ref600:
	.byte $d3
@ref601:
	.byte $d3
@ref602:
	.byte $d3
@ref603:
	.byte $d3
@ref604:
	.byte $d3
@ref605:
	.byte $d3
@ref606:
	.byte $d3
@ref607:
	.byte $d3
@ref608:
	.byte $d3
@ref609:
	.byte $d3
@ref610:
	.byte $d3
@ref611:
	.byte $d3
@ref612:
	.byte $d3
@ref613:
	.byte $d3
@ref614:
	.byte $d3
@ref615:
	.byte $d3
@ref616:
	.byte $d3
@ref617:
	.byte $d3
@ref618:
	.byte $d3
@ref619:
	.byte $d3
@ref620:
	.byte $d3
@ref621:
	.byte $d3
@ref622:
	.byte $d3
@ref623:
	.byte $d3
@ref624:
	.byte $d3
@ref625:
	.byte $d3
@ref626:
	.byte $d3
@ref627:
	.byte $d3
@ref628:
	.byte $d3
@ref629:
	.byte $d3
	.byte $fd
	.word @song2ch4loop
